# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python


pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    PythonPyPy36:
      python.version: 'pypy3'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install pytest pytest-azurepipelines
  displayName: 'Install Python dependencies'

- script: |
    python -m pytest -v
  displayName: 'Run tests'

- script: |
    sudo apt-get update
    sudo apt-get install --yes libsdl2-dev
  displayName: 'Install SDL2'

- script: |
    python -m pip install .
    emnes --help
  displayName: 'Test pip install'
